# Generated by Django 5.0.7 on 2024-10-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='Instructor/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('progress', models.FloatField(default=0.0)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='Learnify_App.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('ENROLLMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learnify_App.courseenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('file', models.FileField(upload_to='course_video_file/')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video', to='Learnify_App.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='INSTRUCTOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Learnify_App.instructor'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learnify_App.login'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='Student/')),
                ('dob', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learnify_App.login')),
            ],
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='Learnify_App.student'),
        ),
    ]
