# Generated by Django 5.0.7 on 2024-10-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learnify_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='VIDEO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Learnify_App.coursevideos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='watched_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
